#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

PKG_NAME="mythtv"

echo "getting sources..."
  if [ ! -d mythtv.git ]; then
    git clone https://github.com/MythTV/mythtv.git -b fixes/0.26 mythtv.git
  fi

  cd mythtv.git
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf $PKG_NAME-$GIT_REV
  cp -R mythtv.git/mythtv $PKG_NAME-$GIT_REV

echo "cleaning sources..."
  rm -rf $PKG_NAME-$GIT_REV/.git

echo "packing sources..."
  tar cvjf $PKG_NAME-$GIT_REV.tar.bz2 $PKG_NAME-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf $PKG_NAME-$GIT_REV

echo "copying tar balls to sources..."
  if [ ! -d ../../sources/ ]; then
    mkdir ../../sources/
  fi
  if [ ! -d ../../sources/$PKG_NAME/ ]; then
    mkdir ../../sources/$PKG_NAME/
  fi
  mv $PKG_NAME-$GIT_REV.tar.bz2 ../../sources/$PKG_NAME/

echo "generate md5 and url files..."
  cd ../..
  md5sum sources/$PKG_NAME/$PKG_NAME-$GIT_REV.tar.bz2 > sources/$PKG_NAME/$PKG_NAME-$GIT_REV.tar.bz2.md5
  # url MUST match the one we're looking for first
  echo "http://ftp.osuosl.org/pub/mythtv/$PKG_NAME-$GIT_REV.tar.bz2" > sources/$PKG_NAME/$PKG_NAME-$GIT_REV.tar.bz2.url
  echo "Source tar balls generated for $PKG_NAME PKG_VERSION=$GIT_REV successfully."
